server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
